SUBROUTINE BNR.INACTIVE.DORM.SELECT

$INSERT ../T24_BP I_COMMON
$INSERT ../T24_BP I_EQUATE
$INSERT I_F.BNR.INACTIVE.DORM.COMMON

GOSUB INIT
GOSUB PROCESS

INIT: 
    RETURN

PROCESS:
    SEL.CMD = 'SSELECT ':FN.ACCOUNT:" WITH CATEGORY EQ ":S.PARAM.CATEG
    AC.LIST = '' ; NO.OF.RECS = '' ; LIST.ERR = ''

    CALL EB.READLIST(SEL.CMD,AC.LIST,'',NO.OF.RECS,LIST.ERR)
    CALL BATCH.BUILD.LIST('',AC.LIST)

    RETURN
END