SUBROUTINE VSL_CustomerDetails

    $INSERT ../T24_BP I_COMMON
    $INSERT ../T24_BP I_EQUATE

    *Category range 6000 to 6999
    IF NOT(COMI MATCHES "'6'3N") THEN ETEXT = 'AC-CATEG.NOT.SAVINGS'

    *Category range 1000 to 1999
    IF NOT(COMI MATCHES "'1'3N") THEN ETEXT = 'AC-CATEG.NOT.INDIVIDUAL'

    RETURN
END
