PROGRAM VSL.READ

    DIR.IN = "../bnk.run/VSL.BP"
    FILE.IN = "TEST.READ"
    
    OPENSEQ DIR.IN, FILE.IN TO Y.FILE.1 THEN
    LOOP
            READSEQ Y.LINE FROM Y.FILE.1 ELSE BREAK
            CRT Y.LINE
        REPEAT
    END ELSE CRT "COULD NOT OPEN ": FILE.IN

    CLOSESEQ Y.FILE.1
END